set -uxe

COMMANDS_FILE="commands.h"
echo "#pragma once" > $COMMANDS_FILE

for i in *.h; do

    if [[ "$i" == "$COMMANDS_FILE" ]]; then continue; fi;
    echo "#include \"$i\"" >> $COMMANDS_FILE
done

echo "// Auto-generated by $0" >> $COMMANDS_FILE